apiVersion: v1
kind: ServiceAccount
metadata:
  name: ptk-node-check
  namespace: ptk-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ptk-audit
  namespace: ptk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptk-audit
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ptk-audit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ptk-audit
subjects:
  - kind: ServiceAccount
    name: ptk-audit
    namespace: ptk-system
